version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/web:/vol/web
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=changeme
      - ALLOWED_HOSTS=localhost
      - TRUSTED_ORIGIN=http://localhost
      - DEBUG=1
    depends_on:
      - db
  frontend:
    build: frontend
    restart: always
    command: yarn run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
      - ./frontend/node_modules:/code/node_modules