# Generated by Django 3.2.13 on 2022-05-19 06:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.IntegerField(choices=[(1, 'Parttime'), (2, 'Contract'), (3, 'Regular')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stamp_type', models.IntegerField(choices=[(1, 'Work Start'), (2, 'Work End'), (3, 'Break Start'), (4, 'Break End')])),
                ('memo', models.CharField(default='', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kintai_kun.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Change Req')], default=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=datetime.timedelta(seconds=36000))),
                ('end_time', models.TimeField(default=datetime.timedelta(seconds=66600))),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kintai_kun.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='worktimestamp',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'stamp_type'), name='unique_stamp_date'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('start_time'), '+', django.db.models.expressions.Value(datetime.timedelta(seconds=14400))))), name='end_gt_start'),
        ),
    ]
