# Generated by Django 3.2.13 on 2022-04-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai_kun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimestamp',
            name='memo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
