# Generated by Django 3.2.13 on 2022-05-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai_kun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worktimestamp',
            name='unique_stamp_date',
        ),
    ]
