# Generated by Django 3.2.13 on 2022-05-20 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kintai_kun', '0002_remove_worktimestamp_unique_stamp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WorkTimestampChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_stamp_type', models.IntegerField(choices=[(1, 'Work Start'), (2, 'Work End'), (3, 'Break Start'), (4, 'Break End')])),
                ('new_stamp_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.TextField(choices=[('POST', 'Create'), ('PUT', 'Update'), ('DELETE', 'Delete')])),
                ('approving_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kintai_kun.employee')),
                ('original_worktimestamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kintai_kun.worktimestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
