# Generated by Django 3.2.13 on 2022-05-30 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kintai_kun', '0002_remove_worktimestamp_unique_stamp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktimestamp',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
