# Generated by Django 3.2.13 on 2022-04-14 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kintai_kun', '0002_worktimestamp_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shift',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='worktimestamp',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='worktimestamp',
            name='stamp_type',
            field=models.IntegerField(choices=[(1, 'Work Start'), (2, 'Work End'), (3, 'Break Start'), (4, 'Break End')], unique_for_date='created_on'),
        ),
    ]
