# Generated by Django 3.2.13 on 2022-04-15 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kintai_kun', '0003_auto_20220414_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimestamp',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='worktimestamp',
            name='stamp_type',
            field=models.IntegerField(choices=[(1, 'Work Start'), (2, 'Work End'), (3, 'Break Start'), (4, 'Break End')], unique_for_date='date'),
        ),
        migrations.AddConstraint(
            model_name='worktimestamp',
            constraint=models.UniqueConstraint(fields=('date', 'stamp_type'), name='unique_stamp_date'),
        ),
    ]
